apiVersion: v1
kind: Service
metadata:
    name: "pgagic-5cb9"
    labels:
        app: "pgagic-5cb9"
spec:
    type: LoadBalancer
    ports:
    - port: 234
      targetPort: 234
      protocol: TCP
      name: http
    selector:
        app: "pgagic-5cb9"