on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: danimalcontainers.azurecr.io
        username: ${{ secrets.acr_danimalcontainers_username }}
        password: ${{ secrets.acr_danimalcontainers_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/5" -f  "5" -t danimalcontainers.azurecr.io/pge2ehttp5:${{ github.sha }} --label dockerfile-path=5
        docker push danimalcontainers.azurecr.io/pge2ehttp5:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_pge2ehttp5_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep pg_e2e_http5805d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace pg_e2e_http5805d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: pg_e2e_http5805d
        container-registry-url: danimalcontainers.azurecr.io
        container-registry-username: ${{ secrets.acr_danimalcontainers_username }}
        container-registry-password: ${{ secrets.acr_danimalcontainers_password }}
        secret-name: pge2ehttp5dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: pg_e2e_http5805d
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          danimalcontainers.azurecr.io/pge2ehttp5:${{ github.sha }}
        imagepullsecrets: |
          pge2ehttp5dockerauth
